// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "go-pet-shop/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Analytics is an autogenerated mock type for the Analytics type
type Analytics struct {
	mock.Mock
}

// GetPopularProducts provides a mock function with given fields: ctx
func (_m *Analytics) GetPopularProducts(ctx context.Context) ([]models.PopularProduct, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPopularProducts")
	}

	var r0 []models.PopularProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.PopularProduct, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.PopularProduct); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PopularProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserOrderHistory provides a mock function with given fields: ctx, email
func (_m *Analytics) GetUserOrderHistory(ctx context.Context, email string) ([]models.OrderDetail, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrderHistory")
	}

	var r0 []models.OrderDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.OrderDetail, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.OrderDetail); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAnalytics creates a new instance of Analytics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalytics(t interface {
	mock.TestingT
	Cleanup(func())
}) *Analytics {
	mock := &Analytics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
