// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "go-pet-shop/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Orders is an autogenerated mock type for the Orders type
type Orders struct {
	mock.Mock
}

// AddOrderItem provides a mock function with given fields: ctx, orderItem
func (_m *Orders) AddOrderItem(ctx context.Context, orderItem models.OrderItem) error {
	ret := _m.Called(ctx, orderItem)

	if len(ret) == 0 {
		panic("no return value specified for AddOrderItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderItem) error); ok {
		r0 = rf(ctx, orderItem)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *Orders) CreateOrder(ctx context.Context, order models.Order) (int, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) (int, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) int); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByID provides a mock function with given fields: ctx, id
func (_m *Orders) GetOrderByID(ctx context.Context, id int) (models.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (models.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) models.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderItemsByOrderID provides a mock function with given fields: ctx, orderID
func (_m *Orders) GetOrderItemsByOrderID(ctx context.Context, orderID int) ([]models.OrderItem, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderItemsByOrderID")
	}

	var r0 []models.OrderItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.OrderItem, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.OrderItem); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrdersByUserEmail provides a mock function with given fields: ctx, email
func (_m *Orders) GetOrdersByUserEmail(ctx context.Context, email string) ([]models.Order, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUserEmail")
	}

	var r0 []models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Order, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Order); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaceOrder provides a mock function with given fields: ctx, userEmail, items
func (_m *Orders) PlaceOrder(ctx context.Context, userEmail string, items []models.OrderItem) (int, error) {
	ret := _m.Called(ctx, userEmail, items)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []models.OrderItem) (int, error)); ok {
		return rf(ctx, userEmail, items)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []models.OrderItem) int); ok {
		r0 = rf(ctx, userEmail, items)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []models.OrderItem) error); ok {
		r1 = rf(ctx, userEmail, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrders creates a new instance of Orders. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrders(t interface {
	mock.TestingT
	Cleanup(func())
}) *Orders {
	mock := &Orders{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
